name: Deploy Serverless Framework with AWS OIDC
description: Deploy Serverless Framework with AWS OIDC
inputs:
  role-to-assume:
    description: Role ARN as same as aws-actions/configure-aws-credentials
    required: true
  aws-region:
    description: Region as same as aws-actions/configure-aws-credentials
    required: true
  args:
    description: serverless command args
    required: false
    default: deploy --verbose
  working-directory:
    description: Working directory
    required: false
    default: .
branding:
  icon: upload-cloud
  color: orange
runs:
  using: composite
  steps:
    - run: npm install -g serverless
      shell: bash
    - uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
    - run: serverless ${{ inputs.args }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
